In [46]:
# Problem 1
import numpy as np
import scipy.linalg.interpolative as slid

a = np.array([[-1.32 , -0.18 , 2.13], [2.64  , -4.68 , 4.65], [1.47  , -4.75 , 6.80]])

#a = np.array([[1 , 0 , 2.02 ], [2 , 2 , 10.03], [3 , 1 , 8.98 ]])

U,sigma,V = np.linalg.svd(a)

sigma = np.diag(sigma)

print(sigma)

print('Number of independent columns : {0}'.format(2))

[[1.42430133e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.20755811e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.72130229e-03]]
Number of independent columns : 3
