In [12]:
import numpy as np
import cv2 as cv

CHECKERBOARD_DIM = (7,10)


objectp3d = np.zeros((1, CHECKERBOARD_DIM[0]
                      * CHECKERBOARD_DIM[1],
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD_DIM[0],
                               0:CHECKERBOARD_DIM[1]].T.reshape(-1, 2)


img1 = cv.imread("checker1.jpg")
# I tired using an iphone but due to high res (12MP) it was taking too long
# Thus I decided to use my webcam and forced it to a 0.9MP (1280x720) and it speeded up the process   
gray1 = cv.cvtColor(img1,cv.COLOR_BGR2GRAY)

criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

ret, corners = cv.findChessboardCorners(gray1, CHECKERBOARD_DIM, cv.CALIB_CB_ADAPTIVE_THRESH + cv.CALIB_CB_NORMALIZE_IMAGE)
if ret == True:
    corners2 = cv.cornerSubPix(gray1,corners, (11,11), (-1,-1),criteria)
     # Draw and display the corners
    cv.drawChessboardCorners(img1, (7,10), corners2, ret)
    cv.imshow('img', img1)
    cv.waitKey(0)
    cv.destroyAllWindows()
else:
    print("Not Found")


In [13]:
# Import required modules
import cv2
import numpy as np
import os
import glob


# Define the dimensions of checkerboard
CHECKERBOARD = (7, 10)


# stop the iteration when specified
# accuracy, epsilon, is reached or
# specified number of iterations are completed.
criteria = (cv2.TERM_CRITERIA_EPS +
			cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)


# Vector for 3D points
threedpoints = []

# Vector for 2D points
twodpoints = []


# 3D points real world coordinates
objectp3d = np.zeros((1, CHECKERBOARD[0]
					* CHECKERBOARD[1],
					3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
							0:CHECKERBOARD[1]].reshape(-1, 2)
prev_img_shape = None


# Extracting path of individual image stored
# in a given directory. Since no path is
# specified, it will take current directory
# jpg files alone
images = glob.glob('*.jpg')

for filename in images:
	image = cv2.imread(filename)
	grayColor = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

	# Find the chess board corners
	# If desired number of corners are
	# found in the image then ret = true
	ret, corners = cv2.findChessboardCorners(
					grayColor, CHECKERBOARD,
					cv2.CALIB_CB_ADAPTIVE_THRESH
					+ cv2.CALIB_CB_FAST_CHECK +
					cv2.CALIB_CB_NORMALIZE_IMAGE)

	# If desired number of corners can be detected then,
	# refine the pixel coordinates and display
	# them on the images of checker board
	if ret == True:
		threedpoints.append(objectp3d)

		# Refining pixel coordinates
		# for given 2d points.
		corners2 = cv2.cornerSubPix(
			grayColor, corners, (11, 11), (-1, -1), criteria)

		twodpoints.append(corners2)

		# Draw and display the corners
		image = cv2.drawChessboardCorners(image,
										CHECKERBOARD,
										corners2, ret)

	#cv2.imshow('img', image)
	#cv2.waitKey(0)

#cv2.destroyAllWindows()

h, w = image.shape[:2]


# Perform camera calibration by
# passing the value of above found out 3D points (threedpoints)
# and its corresponding pixel coordinates of the
# detected corners (twodpoints)
ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera(
	threedpoints, twodpoints, grayColor.shape[::-1], None, None)


# Displaying required output
print(" Camera matrix:")
print(matrix)

print("\n Distortion coefficient:")
print(distortion)

print("\n Rotation Vectors:")
print(r_vecs)

#r_mat = cv.Rodrigues(r_vecs[:])
r_mat = []

for i in range(len(r_vecs)):
    r_mat_1 = np.zeros((3,3))
    cv2.Rodrigues(r_vecs[i],r_mat_1)
    r_mat.append(r_mat_1)

print("\n Rotation Matrix:")
print(r_mat[0])

print("\n Translation Vectors:")
print(t_vecs)


 Camera matrix:
[[934.61611549   0.         655.89814635]
 [  0.         935.62232667 376.69600266]
 [  0.           0.           1.        ]]

 Distortion coefficient:
[[ 1.93401507e-02 -1.51969543e-01  2.53863938e-03 -1.39354180e-04
   1.02012352e-01]]

 Rotation Vectors:
(array([[-0.00613381],
       [ 0.01663303],
       [ 1.57744067]]), array([[-0.17384799],
       [ 0.02338664],
       [ 2.21253925]]), array([[0.02336786],
       [0.08027795],
       [1.55467779]]), array([[-0.23886301],
       [-0.06441354],
       [ 1.72067815]]), array([[0.07360575],
       [0.21027496],
       [1.91619121]]), array([[-0.14606981],
       [-0.12831519],
       [ 1.95087421]]), array([[-0.6757934 ],
       [ 0.02344598],
       [ 1.44725516]]), array([[-0.0939128 ],
       [ 0.05549646],
       [ 1.571369  ]]), array([[ 0.37800552],
       [-0.72767828],
       [ 1.69774162]]), array([[ 0.54210222],
       [-0.57613452],
       [ 1.54067865]]), array([[-0.37585646],
       [ 0.41271379],
      

In [11]:
import numpy as np
import cv2 as cv

CHECKERBOARD_DIM = (7,10)

objectPoints_3D = np.array([[0,0,0],
                      [CHECKERBOARD_DIM[0]-1,0,0],
                      [0,CHECKERBOARD_DIM[0]-1,0],
                      [CHECKERBOARD_DIM[0]-1,CHECKERBOARD_DIM[1]-1,0]])

points_3D = []
points_2D = []

points_3D.append(objectPoints_3D)

img1 = cv.imread("checker3.jpg")
# I tired using an iphone but due to high res (12MP) it was taking too long
# Thus I decided to use my webcam and forced it to a 0.9MP (1280x720) and it speeded up the process   
gray1 = cv.cvtColor(img1,cv.COLOR_BGR2GRAY)

criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

ret, corners = cv.findChessboardCorners(gray1, CHECKERBOARD_DIM, cv.CALIB_CB_ADAPTIVE_THRESH + cv.CALIB_CB_NORMALIZE_IMAGE)

points_3D.append(objectPoints_3D)

points_2D.append( np.array( [corners[0],corners[CHECKERBOARD_DIM[0]-1], corners[(CHECKERBOARD_DIM[0]*CHECKERBOARD_DIM[1])-(1+CHECKERBOARD_DIM[0])] ,corners[(CHECKERBOARD_DIM[0]*CHECKERBOARD_DIM[1])-1]] ) )

cv.drawChessboardCorners(img1, (2,2), np.array([corners2[0],corners2[6],corners2[63],corners2[69]]), ret)
cv.imshow('img', img1)
cv.waitKey(0)
cv.destroyAllWindows()


