In [ ]:
import numpy as np
import cv2 as cv

CHECKERBOARD_DIM = (7,10)


objectp3d = np.zeros((1, CHECKERBOARD_DIM[0]
                      * CHECKERBOARD_DIM[1],
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD_DIM[0],
                               0:CHECKERBOARD_DIM[1]].T.reshape(-1, 2)


img1 = cv.imread("checker1.jpg")
# I tired using an iphone but due to high res (12MP) it was taking too long
# Thus I decided to use my webcam and forced it to a 0.9MP (1280x720) and it speeded up the process   
gray1 = cv.cvtColor(img1,cv.COLOR_BGR2GRAY)

criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

ret, corners = cv.findChessboardCorners(gray1, CHECKERBOARD_DIM, cv.CALIB_CB_ADAPTIVE_THRESH + cv.CALIB_CB_NORMALIZE_IMAGE)
if ret == True:
    corners2 = cv.cornerSubPix(gray1,corners, (11,11), (-1,-1),criteria)
     # Draw and display the corners
    cv.drawChessboardCorners(img1, (7,10), corners2, ret)
    cv.imshow('img', img1)
    cv.waitKey(0)
    cv.destroyAllWindows()
else:
    print("Not Found")


In [35]:
# Import required modules
import cv2
import numpy as np
import os
import glob


# Define the dimensions of checkerboard
CHECKERBOARD = (7, 10)


# stop the iteration when specified
# accuracy, epsilon, is reached or
# specified number of iterations are completed.
criteria = (cv2.TERM_CRITERIA_EPS +
			cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)


# Vector for 3D points
threedpoints = []

# Vector for 2D points
twodpoints = []


# 3D points real world coordinates
objectp3d = np.zeros((1, CHECKERBOARD[0]
					* CHECKERBOARD[1],
					3), np.float32)

objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
							0:CHECKERBOARD[1]].T.reshape(-1, 2)

prev_img_shape = None


# Extracting path of individual image stored
# in a given directory. Since no path is
# specified, it will take current directory
# jpg files alone
images = glob.glob('*.jpg')

for filename in images:
	image = cv2.imread(filename)
	grayColor = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

	# Find the chess board corners
	# If desired number of corners are
	# found in the image then ret = true
	ret, corners = cv2.findChessboardCorners(
					grayColor, CHECKERBOARD,
					cv2.CALIB_CB_ADAPTIVE_THRESH
					+ cv2.CALIB_CB_FAST_CHECK +
					cv2.CALIB_CB_NORMALIZE_IMAGE)

	# If desired number of corners can be detected then,
	# refine the pixel coordinates and display
	# them on the images of checker board
	if ret == True:
		threedpoints.append(objectp3d)

		# Refining pixel coordinates
		# for given 2d points.
		corners2 = cv2.cornerSubPix(
			grayColor, corners, (11, 11), (-1, -1), criteria)

		twodpoints.append(corners2)

		# Draw and display the corners
		image = cv2.drawChessboardCorners(image,
										CHECKERBOARD,
										corners2, ret)

	#cv2.imshow('img', image)
	#cv2.waitKey(0)

#cv2.destroyAllWindows()

h, w = image.shape[:2]


# Perform camera calibration by
# passing the value of above found out 3D points (threedpoints)
# and its corresponding pixel coordinates of the
# detected corners (twodpoints)
ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera(
	threedpoints, twodpoints, grayColor.shape[::-1], None, None)


# Displaying required output
print(" Camera matrix:")
print(matrix)

print("\n Distortion coefficient:")
print(distortion)

print("\n Rotation Vectors:")
print(r_vecs)

#r_mat = cv.Rodrigues(r_vecs[:])
r_mat = []

for i in range(len(r_vecs)):
    r_mat_1 = np.zeros((3,3))
    cv2.Rodrigues(r_vecs[i],r_mat_1)
    r_mat.append(r_mat_1)

print("\n Rotation Matrix:")
print(r_mat[0])

print("\n Translation Vectors:")
print(t_vecs)


 Camera matrix:
[[934.6161155    0.         655.8981464 ]
 [  0.         935.62232668 376.69600261]
 [  0.           0.           1.        ]]

 Distortion coefficient:
[[ 1.93401506e-02 -1.51969542e-01  2.53863936e-03 -1.39354163e-04
   1.02012352e-01]]

 Rotation Vectors:
(array([[-0.00613381],
       [ 0.01663303],
       [ 1.57744067]]), array([[-0.17384799],
       [ 0.02338664],
       [ 2.21253925]]), array([[0.02336786],
       [0.08027795],
       [1.55467779]]), array([[-0.23886301],
       [-0.06441354],
       [ 1.72067815]]), array([[0.07360575],
       [0.21027496],
       [1.91619121]]), array([[-0.14606981],
       [-0.12831519],
       [ 1.95087421]]), array([[-0.6757934 ],
       [ 0.02344598],
       [ 1.44725516]]), array([[-0.0939128 ],
       [ 0.05549646],
       [ 1.571369  ]]), array([[ 0.37800552],
       [-0.72767828],
       [ 1.69774162]]), array([[ 0.54210222],
       [-0.57613452],
       [ 1.54067865]]), array([[-0.37585646],
       [ 0.41271379],
      

In [43]:
import numpy as np
import cv2 as cv
import glob

# I tired using an iphone but due to high res (12MP) it was taking too long
# Thus I decided to use my webcam and forced it to a 0.9MP (1280x720) and it speeded up the process  

CHECKERBOARD_DIM = (7,10)

objectPoints_3D = np.array([[0,0,0],
                      [CHECKERBOARD_DIM[0]-1,0,0],
                      [0,CHECKERBOARD_DIM[0]-1,0],
                      [CHECKERBOARD_DIM[0]-1,CHECKERBOARD_DIM[1]-1,0]],np.float32)

objectPoints_3D = np.zeros((1, CHECKERBOARD[0]* CHECKERBOARD[1],3), np.float32)

objectPoints_3D[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],0:CHECKERBOARD[1]].T.reshape(-1, 2)

points_3D = []
points_2D = []

image = glob.glob('*.jpg')

for filename in image:
    img = cv.imread(filename)
 
    gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)

    ret, corners = cv.findChessboardCorners(gray, CHECKERBOARD_DIM,None)

    points_3D.append(objectPoints_3D)
    four_corners = np.array([corners[0],corners[6],corners[63],corners[69]],np.float32)
    points_2D.append(corners)

    #cv.drawChessboardCorners(img, (2,2), four_corners, ret)
    #cv.imshow('img', img)
    #cv.waitKey(0)
    #cv.destroyAllWindows()


ret, matrix, distortion, r_vecs, t_vecs = cv.calibrateCamera(points_3D, points_2D, gray.shape[::-1], None, None)

# Displaying required output
print(" Camera matrix:")
print(matrix)

r_mat = []

for i in range(len(r_vecs)):
    r_mat_i = np.zeros((3,3))
    cv.Rodrigues(r_vecs[i],r_mat_i)
    r_mat.append(r_mat_i)
    print("\nExtrensic Matrix for Image {0} :-".format(i+1))
    print("\n Rotation Matrix:")
    print(r_mat[i])
    print("\n Translation Vectors:")
    print(t_vecs[i])

 Camera matrix:
[[936.03169921   0.         651.66737484]
 [  0.         936.65257154 375.67629189]
 [  0.           0.           1.        ]]

Extrensic Matrix for Image 1 :-

 Rotation Matrix:
[array([[-0.0071371 , -0.99989578,  0.01254932],
       [ 0.9999077 , -0.00699097,  0.01165002],
       [-0.01156107,  0.01263131,  0.99985339]])]

 Translation Vectors:
[[ 3.13348858]
 [-2.68607223]
 [13.58661587]]

Extrensic Matrix for Image 2 :-

 Rotation Matrix:
[array([[-0.0071371 , -0.99989578,  0.01254932],
       [ 0.9999077 , -0.00699097,  0.01165002],
       [-0.01156107,  0.01263131,  0.99985339]]), array([[-0.59448786, -0.79585015, -0.11492046],
       [ 0.79306808, -0.60390691,  0.0796208 ],
       [-0.13276749, -0.04380614,  0.99017868]])]

 Translation Vectors:
[[ 4.99690892]
 [ 0.83974576]
 [20.45122829]]

Extrensic Matrix for Image 3 :-

 Rotation Matrix:
[array([[-0.0071371 , -0.99989578,  0.01254932],
       [ 0.9999077 , -0.00699097,  0.01165002],
       [-0.01156107,  0.01